version: '2'
services:
  web:
    image: node:4.6
    volumes:
      - "./word-finder:/app"
    working_dir: /app
    restart: always
    expose:
      - 3000
    ports:
      - "8080:3000"
    command: node start.js